/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppDemo {}
  interface AppDemoAttributes extends StencilHTMLAttributes {}

  interface AppTest {}
  interface AppTestAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppDemo': Components.AppDemo;
    'AppTest': Components.AppTest;
  }

  interface StencilIntrinsicElements {
    'app-demo': Components.AppDemoAttributes;
    'app-test': Components.AppTestAttributes;
  }


  interface HTMLAppDemoElement extends Components.AppDemo, HTMLStencilElement {}
  var HTMLAppDemoElement: {
    prototype: HTMLAppDemoElement;
    new (): HTMLAppDemoElement;
  };

  interface HTMLAppTestElement extends Components.AppTest, HTMLStencilElement {}
  var HTMLAppTestElement: {
    prototype: HTMLAppTestElement;
    new (): HTMLAppTestElement;
  };

  interface HTMLElementTagNameMap {
    'app-demo': HTMLAppDemoElement
    'app-test': HTMLAppTestElement
  }

  interface ElementTagNameMap {
    'app-demo': HTMLAppDemoElement;
    'app-test': HTMLAppTestElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
